# Generated by Django 5.2.3 on 2026-02-26 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('components', '0020_address_encounter_attachment_encounter_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('encounter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, help_text='Logical id of this artifact', max_length=64, null=True)),
                ('implicitRules', models.URLField(blank=True, help_text='Rules under which this content was created', max_length=1024, null=True)),
                ('language', models.CharField(blank=True, help_text='Language of the resource content', max_length=16, null=True)),
                ('container_id', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('registered', 'Registered'), ('preliminary', 'Preliminary'), ('final', 'Final'), ('amended', 'Amended'), ('corrected', 'Corrected'), ('cancelled', 'Cancelled'), ('entered-in-error', 'Entered in Error'), ('unknown', 'Unknown')], max_length=32)),
                ('effectiveDateTime', models.DateTimeField(blank=True, null=True)),
                ('effectiveInstant', models.DateTimeField(blank=True, null=True)),
                ('issued', models.DateTimeField(blank=True, null=True)),
                ('valueString', models.CharField(blank=True, max_length=1024, null=True)),
                ('valueBoolean', models.BooleanField(blank=True, null=True)),
                ('valueInteger', models.IntegerField(blank=True, null=True)),
                ('valueDateTime', models.DateTimeField(blank=True, null=True)),
                ('valueTime', models.TimeField(blank=True, null=True)),
                ('note', models.JSONField(blank=True, null=True)),
                ('basedOn', models.ManyToManyField(blank=True, related_name='based_on_observations', to='components.reference')),
                ('bodySite', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_body_sites', to='components.codeableconcept')),
                ('category', models.ManyToManyField(blank=True, related_name='observation_categories', to='components.codeableconcept')),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='components.codeableconcept')),
                ('container_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('dataAbsentReason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_data_absent_reasons', to='components.codeableconcept')),
                ('derivedFrom', models.ManyToManyField(blank=True, related_name='derived_observations', to='components.reference')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_observations', to='components.reference')),
                ('effectivePeriod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='effective_observations', to='components.period')),
                ('encounter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observations', to='encounter.encounter')),
                ('focus', models.ManyToManyField(blank=True, related_name='focus_observations', to='components.reference')),
                ('hasMember', models.ManyToManyField(blank=True, related_name='member_of', to='observation.observation')),
                ('interpretation', models.ManyToManyField(blank=True, related_name='observation_interpretations', to='components.codeableconcept')),
                ('meta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.metaelement')),
                ('method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_methods', to='components.codeableconcept')),
                ('partOf', models.ManyToManyField(blank=True, related_name='part_of_observations', to='components.reference')),
                ('performer', models.ManyToManyField(blank=True, related_name='performed_observations', to='components.reference')),
                ('specimen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specimen_observations', to='components.reference')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_observations', to='components.reference')),
                ('text', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_resource', to='components.narrative')),
                ('valueCodeableConcept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_value_cc', to='components.codeableconcept')),
                ('valuePeriod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_value_periods', to='components.period')),
                ('valueQuantity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_values', to='components.quantity')),
                ('valueRange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation_value_ranges', to='components.range')),
            ],
            options={
                'db_table': 'observation',
            },
        ),
        migrations.CreateModel(
            name='ObservationComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('valueString', models.CharField(blank=True, max_length=1024, null=True)),
                ('valueBoolean', models.BooleanField(blank=True, null=True)),
                ('valueInteger', models.IntegerField(blank=True, null=True)),
                ('valueDateTime', models.DateTimeField(blank=True, null=True)),
                ('valueTime', models.TimeField(blank=True, null=True)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_components', to='components.codeableconcept')),
                ('dataAbsentReason', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_component_data_absent_reasons', to='components.codeableconcept')),
                ('interpretation', models.ManyToManyField(blank=True, related_name='obs_component_interpretations', to='components.codeableconcept')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='observation.observation')),
                ('valueCodeableConcept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_component_value_cc', to='components.codeableconcept')),
                ('valuePeriod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_component_value_periods', to='components.period')),
                ('valueQuantity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_component_values', to='components.quantity')),
                ('valueRange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_component_value_ranges', to='components.range')),
            ],
            options={
                'db_table': 'observation_component',
            },
        ),
        migrations.CreateModel(
            name='ObservationReferenceRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('age', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_reference_ranges', to='components.range')),
                ('appliesTo', models.ManyToManyField(blank=True, related_name='obs_ref_range_applies_to', to='components.codeableconcept')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='observation.observationcomponent')),
                ('high', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_ref_range_highs', to='components.quantity')),
                ('low', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_ref_range_lows', to='components.quantity')),
                ('normalValue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_ref_range_normal_values', to='components.codeableconcept')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reference_ranges', to='observation.observation')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_ref_range_types', to='components.codeableconcept')),
            ],
            options={
                'db_table': 'observation_reference_range',
            },
        ),
        migrations.CreateModel(
            name='ObservationTriggeredBy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fhir_id', models.CharField(blank=True, max_length=64, null=True)),
                ('modifierExtension', models.JSONField(blank=True, null=True)),
                ('type', models.CharField(choices=[('reflex', 'Reflex'), ('repeat', 'Repeat'), ('re-run', 'Re-run')], max_length=16)),
                ('reason', models.CharField(blank=True, max_length=512, null=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_by', to='observation.observation')),
                ('triggering_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_observations', to='observation.observation')),
            ],
            options={
                'db_table': 'observation_triggered_by',
            },
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['status'], name='observation_status_cdb912_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['effectiveDateTime'], name='observation_effecti_d6ff33_idx'),
        ),
        migrations.AddIndex(
            model_name='observation',
            index=models.Index(fields=['issued'], name='observation_issued_c57003_idx'),
        ),
    ]
